-- MySQL Script generated by MySQL Workbench
-- 06/25/17 19:26:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pdi_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pdi_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdi_db` DEFAULT CHARACTER SET utf8 ;
USE `pdi_db` ;

-- -----------------------------------------------------
-- Table `pdi_db`.`Parlamentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`parlamentar` (
  `idParlamentar` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `legislatura` INT NOT NULL,
  PRIMARY KEY (`idParlamentar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_db`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`uf` (
  `idUF` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(3) NOT NULL,
  `cota` DOUBLE NOT NULL,
  PRIMARY KEY (`idUF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_db`.`Partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`partido` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPartido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_db`.`TipoDespesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`tipodespesa` (
  `idTipoDespesa` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `tipoDocumento` INT NOT NULL,
  PRIMARY KEY (`idTipoDespesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_db`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `cpfCnpj` VARCHAR(15) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_db`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`data` (
  `idData` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  PRIMARY KEY (`idData`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_db`.`Despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pdi_db`.`despesa` (
  `idParlamentar` INT NOT NULL,
  `idDespesa` INT NOT NULL AUTO_INCREMENT,
  `idUF` INT NOT NULL,
  `idPartido` INT NOT NULL,
  `idFornecedor` INT NOT NULL,
  `idData` INT NOT NULL,
  `idTipoDespesa` INT NOT NULL,
  `valorDespesa` DOUBLE NOT NULL,
  INDEX `fk_Despesa_Parlamentar_idx` (`idParlamentar` ASC),
  INDEX `fk_Despesa_UF1_idx` (`idUF` ASC),
  INDEX `fk_Despesa_Partido1_idx` (`idPartido` ASC),
  INDEX `fk_Despesa_Fornecedor1_idx` (`idFornecedor` ASC),
  INDEX `fk_Despesa_Data1_idx` (`idData` ASC),
  INDEX `fk_Despesa_TipoDespesa1_idx` (`idTipoDespesa` ASC),
  PRIMARY KEY (`idDespesa`),
  CONSTRAINT `fk_Despesa_Parlamentar`
    FOREIGN KEY (`idParlamentar`)
    REFERENCES `pdi_db`.`parlamentar` (`idParlamentar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despesa_UF1`
    FOREIGN KEY (`idUF`)
    REFERENCES `pdi_db`.`uf` (`idUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despesa_Partido1`
    FOREIGN KEY (`idPartido`)
    REFERENCES `pdi_db`.`partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despesa_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `pdi_db`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despesa_Data1`
    FOREIGN KEY (`idData`)
    REFERENCES `pdi_db`.`data` (`idData`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Despesa_TipoDespesa1`
    FOREIGN KEY (`idTipoDespesa`)
    REFERENCES `pdi_db`.`tipodespesa` (`idTipoDespesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
