  cubes:
    build: .
    ports:
     - "8000:8000"
     - "5000:5000"
    environment:
      DB_URL: mysql://root:root123@mysql/pdi_db
    volumes:
      - ./cubes:/cubes
    links:
      - mysql

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pdi_db
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d